name: Test AzCopy

on:
  push:
    branches:
    - master

jobs:
  test-azcopy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - run: azcopy --version
